Repository elaimaz/BrackeysGameJam-2020.1, pull requests merged in 2020-02, with the labels that each got.

#29 Fix #12 Create Player Jump
  Brackeys Game Jam 2020.1/Assets/Scripts/PlayerScript.cs
Labels: Programming

#31 Fix #30 Change Player movimentation to FixedUpdate
  Brackeys Game Jam 2020.1/Assets/Scripts/PlayerScript.cs
Labels: Programming

#16 Created Script for Basic AI
  Brackeys Game Jam 2020.1/Assets/Animations.meta
  Brackeys Game Jam 2020.1/Assets/Animations/Enemy.meta
  Brackeys Game Jam 2020.1/Assets/Animations/Enemy/BasicEnemyAnime.controller
  Brackeys Game Jam 2020.1/Assets/Animations/Enemy/BasicEnemyAnime.controller.meta
  Brackeys Game Jam 2020.1/Assets/Animations/Enemy/BasicEnemy_Follow.anim
  Brackeys Game Jam 2020.1/Assets/Animations/Enemy/BasicEnemy_Follow.anim.meta
  Brackeys Game Jam 2020.1/Assets/Animations/Enemy/BasicEnemy_Ideal.anim
  Brackeys Game Jam 2020.1/Assets/Animations/Enemy/BasicEnemy_Ideal.anim.meta
  Brackeys Game Jam 2020.1/Assets/Animations/Enemy/BasicEnemy_MeleeAttack.anim
  Brackeys Game Jam 2020.1/Assets/Animations/Enemy/BasicEnemy_MeleeAttack.anim.meta
  Brackeys Game Jam 2020.1/Assets/Animations/Enemy/BasicEnemy_TakeDamage.anim
  Brackeys Game Jam 2020.1/Assets/Animations/Enemy/BasicEnemy_TakeDamage.anim.meta
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/BasicEnemy.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/BasicEnemy/BasicEnemy.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/BasicEnemy/BasicEnemy.cs.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/BasicEnemy/BasicEnemy_Follow.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/BasicEnemy/BasicEnemy_Follow.cs.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/EnemyBase.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/EnemyBase.cs.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/test.txt
  Brackeys Game Jam 2020.1/Assets/Scripts/test.txt.meta
Labels: Programming

#42 Fix #41 Import Main Character idle animation
  Brackeys Game Jam 2020.1/Assets/Audio/Music.meta
  Brackeys Game Jam 2020.1/Assets/Audio/Sound Effects.meta
  Brackeys Game Jam 2020.1/Assets/Sprite.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/IdleAnimation.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/IdleAnimation/Space_Miner_Idle.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/IdleAnimation/Space_Miner_Idle.png.meta
  Brackeys Game Jam 2020.1/Assets/prefabs.meta
Labels: Art

#48 Fix #47 Use Proper Sprite to the player
  Brackeys Game Jam 2020.1/Assets/Audio/Music.meta
  Brackeys Game Jam 2020.1/Assets/Audio/Sound Effects.meta
  Brackeys Game Jam 2020.1/Assets/prefabs/Player.prefab
  Brackeys Game Jam 2020.1/Assets/prefabs/Player.prefab.meta
Labels: Art

#50 Fix #49 Animate Player with iddle animation
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/IdlleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/IdlleAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/Sprite.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/Sprite.controller.meta
Labels: Art

#52 Fix #51 Flip Sprite when Moving
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
Labels: Art, Programming

#55 Fix #54 Animate Player Run Animation
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerAnimatorController.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerAnimatorController.cs.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/IdleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/RunAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/RunAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/Space_Miner_Idle_Fixed_again_0.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/Sprite.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/Sprite.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Idle/Space_Miner_Idle_Fixed_again.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Running/Space_Miner_Running_FIxed.png.meta
  Brackeys Game Jam 2020.1/Assets/prefabs/Player.prefab
Labels: Art, Programming

#57 Fix #56 Import Main Character Death Sprites
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Death.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Death/Space_Miner_Death1.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Death/Space_Miner_Death1.png.meta
Labels: Art

#59 Fix #58 Import Main Character Jump Sprites
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Jump.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Jump/Space_Miner_Jump.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Jump/Space_Miner_Jump.png.meta
Labels: Art

#61 Fix #60 Import Main Character Melee Attack
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/MeleeAttack.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/MeleeAttack/Miner_Arm_Gun_Melee_Attack.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/MeleeAttack/Miner_Arm_Gun_Melee_Attack.png.meta
Labels: Art

#63 Fix #62 Import Main Character Ranged Attack
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/RangedAttack.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/RangedAttack/Miner_Arm_Gun_Ranged_Attack.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/RangedAttack/Miner_Arm_Gun_Ranged_Attack.png.meta
Labels: Art

#69 Fix #65 Animate Player Jump
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerAnimatorController.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/JumpAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/JumpAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/Sprite.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Jump/Space_Miner_Jump.png.meta
Labels: Art, Programming

#74 Fix #68 Create footstep sound
  .gitignore
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank.meta
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset
  Brackeys Game Jam 2020.1/Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Audio.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Audio/FMODPlayer.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Audio/FMODPlayer.cs.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/RunAnimation.anim
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank.meta
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/prefabs/Player.prefab
Labels: Audio

#76 Fix #71 Create jump sound
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Audio/FMODPlayer.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/JumpAnimation.anim
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#78 Fix #72 Create landing sound
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/JumpAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/RunAnimation.anim
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#77 Fix #75 Resize sprite scale
  Brackeys Game Jam 2020.1/Assets/Audio/Music.meta
  Brackeys Game Jam 2020.1/Assets/Audio/Sound Effects.meta
  Brackeys Game Jam 2020.1/Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/JumpAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/RunAnimation.anim
  Brackeys Game Jam 2020.1/Assets/prefabs/Player.prefab
Labels: Art

#84 Fix #64 Animate Player Death
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerAnimatorController.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/DeathAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/Sprite.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Death/Space_Miner_Death1.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Death/Space_Miner_Death1.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Death/Space_Miner_Death_FIxed.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Death/Space_Miner_Death_FIxed.png.meta
Labels: Art

#86 Fix #85 Add Arrow and Life Bar
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Arrow.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Arrow/Aimer1.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Arrow/Aimer1.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/HealthBar.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/HealthBar/Health_Bar-1.png.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/HealthBar/Health_Bar-1.png.png.meta
Labels: Art

#94 Fix #93 fix fmod build path
  Brackeys Game Jam 2020.1/Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank.meta
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.bank.meta
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank.meta
Labels: Art, bug

#95 Fix #92 Adjustmens In Melee Attack
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Weapon/MeleeWeapon.cs
Labels: Programming

#97 Fix #96 Import Portal Jumping animation
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/PortalJump.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/PortalJump/Space_Miner_Portal.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/PortalJump/Space_Miner_Portal.png.meta
Labels: Art

#100 Fix #99 Lower footstep volume
  .gitignore
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset
  Brackeys Game Jam 2020.1/Assets/Plugins/FMOD/Cache/Editor/FMODStudioCache.asset.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/RunAnimation.anim
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
Labels: Audio

#101 Fix #98 Animate Portal Jump
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/PortalJump/Space_Miner_Portal.png.meta
Labels: Art

#108 Fix #102 Create Jump Portal Clip Animation
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerAnimatorController.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/JumpPortalAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/JumpPortalAnimation.anim.meta
Labels: Art

#110 Fix #109 Fix clip animation on JumpPortal Animation
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/JumpPortalAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/Sprite.controller
Labels: Art

#112 Fix #111 Hide Weapon in Jump
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/SpriteScript.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/SpriteScript/WeaponHandler.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/SpriteScript/WeaponHandler.cs.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/JumpPortalAnimation.anim
Labels: Art

#114 Fix #113 Show Portal In Jump Portal Animation
  Brackeys Game Jam 2020.1/Assets/Prefabs/Player.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/SpriteScript/WeaponHandler.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/JumpPortalAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/PortalIdle.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/PortalIdle.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/PortalSprite.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/PortalSprite.controller.meta
Labels: Art

#116 Fix #25 Create main theme
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Music.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Music.bank.meta
  Brackeys Game Jam 2020.1/Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Music.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Music.bank.meta
Labels: Audio

#117 Fix #115 Stop Player Move When Jumping Into Portal
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/SpriteScript/WeaponHandler.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/JumpPortalAnimation.anim
Labels: Art, Programming

#118 Fix #66 Create melee attack sound
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Prefabs/Player.prefab
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Weapon/Audio.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Weapon/Audio/FMODWeaponPlayer.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Weapon/Audio/FMODWeaponPlayer.cs.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/MeleeAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#120 Fix #119 Create portal sound
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Portal.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Portal/Audio.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Portal/Audio/FMODPortal.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Portal/Audio/FMODPortal.cs.meta
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#123 Fix #122 Replace drill sample
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
Labels: Audio

#124 Fix #67 Add ranged weapon sound
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Weapon/Audio/FMODMeleeWeaponPlayer.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Weapon/Audio/FMODMeleeWeaponPlayer.cs.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Weapon/Audio/FMODRangedWeaponPlayer.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Weapon/Audio/FMODRangedWeaponPlayer.cs.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/RangedAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#127 Fix #126 flipping and aim of character
  Brackeys Game Jam 2020.1/Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerAnimatorController.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/RangedWeapon.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/Sprite.controller
Labels: Programming

#128 Fix #125 Create death sound
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Audio/FMODPlayer.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#133 Fix #132 Create Player and Projectile Layer
  Brackeys Game Jam 2020.1/Assets/Prefabs/Bullet.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Player.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/ProjectSettings/Physics2DSettings.asset
  Brackeys Game Jam 2020.1/ProjectSettings/QualitySettings.asset
  Brackeys Game Jam 2020.1/ProjectSettings/TagManager.asset
Labels: Programming

#135 Fix #17 Create Portal Mechanic Mockup
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
Labels: Programming

#138 Fix #131 fixed flip in melee and added Charged up range weapon
  Brackeys Game Jam 2020.1/Assets/Prefabs/Player.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Weapon/PlayerWeapons.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Weapon/RangedWeapon.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/Arrow.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/Arrow.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/ArrowAimAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/ArrowAimAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/RangedAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Arrow/Aimer1.png.meta
Labels: Programming

#142 Bgj#141
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
Labels: Programming

#144 Fix #143 Import Blob Sprites
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Attack.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Attack/Blob_Attack.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Attack/Blob_Attack.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Death.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Death/Blob_Death.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Death/Blob_Death.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Idle.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Idle/Blob_Idle.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Idle/Blob_Idle.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Run.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Run/Blob_Running1.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Run/Blob_Running1.png.meta
Labels: Art

#147 Fix #145 Setup Blob Animations
  Brackeys Game Jam 2020.1/Assets/Prefabs/Blob.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Blob.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/BlobSprite.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/BlobSprite.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/IdleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/IdleAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Idle/Blob_Idle.png.meta
Labels: Art

#149 Fix #148 Setup Blob Death Animation
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Blob.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Blob/BlobTests.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Blob/BlobTests.cs.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/BlobSprite.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/DeathAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/IdleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Death/Blob_Death.png.meta
Labels: Art

#151 Fix #150 Setup Blob Walk/Run Animation
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Blob/BlobTests.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/BlobSprite.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/RunAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/RunAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Run/Blob_Running1.png.meta
Labels: Art

#153 Fix #152 Setup Blob Attack Animation
  Brackeys Game Jam 2020.1/Assets/Prefabs/Blob.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Blob/BlobTests.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Attack/Blob_Attack.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/AttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/AttackAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/BlobSprite.controller
Labels: Art

#155 Fix #154 Import Skeleton Sprites
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Attack.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Attack/Skeleton_Attack1.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Attack/Skeleton_Attack1.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Bone.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Bone/Bone_Projectile.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Bone/Bone_Projectile.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Death.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Death/Skeleton_Death.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Death/Skeleton_Death.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Idle.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Idle/Skeleton_Idle.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Idle/Skeleton_Idle.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Walk.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Walk/Skeleton_Walk.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Walk/Skeleton_Walk.png.meta
Labels: Art

#157 Fix #156 Setup Skeleton Idle Animation
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Idle/Skeleton_Idle.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/IdleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/IdleAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/SkeletonSprite.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/SkeletonSprite.controller.meta
Labels: Art

#159 Fix #158 Setup Skeleton Death Animation
  Brackeys Game Jam 2020.1/Assets/Prefabs/Skeleton.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Skeleton.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Death/Skeleton_Death.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/DeathAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/SkeletonSprite.controller
Labels: Art

#161 Fix #160 Skeleton Walk Animation Setup
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/SkeletonSprite.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Walk/RunAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Walk/RunAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Walk/Skeleton_Walk.png.meta
Labels: Art

#163 Fix #162 Skeleton Attack Animation Setup
  Brackeys Game Jam 2020.1/Assets/Prefabs/Skeleton.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Attack/Skeleton_Attack1.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/AttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/AttackAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/RunAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/RunAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/SkeletonSprite.controller
Labels: Art

#165 Fix #164 Add Collider to BLob Enemy
  Brackeys Game Jam 2020.1/Assets/Prefabs/Blob.prefab
Labels: Programming

#167 Fix #166 Add Collider to Skeleton Enemy
  Brackeys Game Jam 2020.1/Assets/Prefabs/Blob.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Skeleton.prefab
Labels: Programming

#176 Fix #170 Add blob walk sound
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Blob/Audio.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Blob/Audio/FMODBlob.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Blob/Audio/FMODBlob.cs.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/BlobSprite.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/RunAnimation.anim
Labels: Audio

#182 Fix #181 Fix Blob Walk/Run Animation
  Brackeys Game Jam 2020.1/Assets/Prefabs/BlobEnemy.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/RunAnimation.anim
Labels: Art

#189 Fix #187 Create gun charge sound
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scenes/Wesley's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Weapon/Audio/FMODRangedWeaponPlayer.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/Weapon/PlayerWeapons.cs
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#190 Fix #172 Create blob death sound
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Blob/Audio/FMODBlob.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/IdleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#192 Fix #191 Create New Portal Animation
  Brackeys Game Jam 2020.1/Assets/Prefabs/Portal.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Portal.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/PortalAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/PortalAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/PortalSprite 1.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Animations/PortalSprite 1.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Player/Portal/Portal.png.meta
Labels: Art

#193 Fix #177 Create Bone projectile Setup
  Brackeys Game Jam 2020.1/Assets/Prefabs/BoneProjectile.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
Labels: Programming

#204 Fix #203 Fix Skeleton method override
  Brackeys Game Jam 2020.1/Assets/BoneScript.cs
  Brackeys Game Jam 2020.1/Assets/SkeletonEnemy.cs
Labels: Programming

#206 Fix #205 Import Eye Boss Sprites
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Eye-Boss_Projectile.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Eye-Boss_Projectile.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Eye_Boss_Death1.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Eye_Boss_Death1.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Eye_Boss_Melee_Attack.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Eye_Boss_Melee_Attack.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Eye_Boss_Ranged_Attack.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Eye_Boss_Ranged_Attack.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Eye_Boss_Walking1.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Eye_Boss_Walking1.png.meta
Labels: Art

#213 Fix #207 Eye Boss Idle Animation Setup
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/EyeBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/EyeBoss.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/EyeBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/EyeBoss.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/IdleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/IdleAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Death.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Death/Eye_Boss_Death1.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Death/Eye_Boss_Death1.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Idle.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Idle/Eye_Boss_Idle.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Idle/Eye_Boss_Idle.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Melee.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Melee/Eye_Boss_Melee_Attack.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Melee/Eye_Boss_Melee_Attack.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Projectile.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Projectile/Eye-Boss_Projectile.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Projectile/Eye-Boss_Projectile.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Ranged.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Ranged/Eye_Boss_Ranged_Attack.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Ranged/Eye_Boss_Ranged_Attack.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Run.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Run/Eye_Boss_Walking1.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Run/Eye_Boss_Walking1.png.meta
Labels: Art

#215 Fix #209 Eye Boss Death ANimation Setup
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/DeathAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/EyeBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Death/Eye_Boss_Death1.png.meta
Labels: Art

#216 Fix #208 Eye Boss Walking Animation Setup
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/EyeBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/RunAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/RunAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Run/Eye_Boss_Walking1.png.meta
Labels: Art

#217 Fix #210 Eye Boss Melee Attack Animation Setup
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/EyeBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/MeleeAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/MeleeAttackAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Melee/Eye_Boss_Melee_Attack.png.meta
Labels: Art

#218 Fix #211 Eye Boss Ranged Attack Animation Setup
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/EyeBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/RangedAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/RangedAttackAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Ranged/Eye_Boss_Ranged_Attack.png.meta
Labels: Art

#220 Fix #219 Eye Boss Beam Animation Setup
  Brackeys Game Jam 2020.1/Assets/Prefabs/EyeBossProjectile.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/EyeBossProjectile.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/EyeBossProjectile.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/EyeBossProjectile.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/EyeBossProjectile.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/EyeBossProjectile.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Projectile/Eye-Boss_Projectile.png.meta
Labels: Art

#223 Fix #221 Setup Eye Boss Animator Rules
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/EyeBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/MeleeAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/RangedAttackAnimation.anim
Labels: Art, Programming

#226 Fix #224 Import Shield Boss Sprite
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Death.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Death/Shield_Boss_Death.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Death/Shield_Boss_Death.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Idle.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Idle/Shield_Boss_Idle_w_spike.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Idle/Shield_Boss_Idle_w_spike.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Projectile.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Projectile/Shield_Boss_Projectile.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Projectile/Shield_Boss_Projectile.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Ranged.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Ranged/Shield_Boss_Ranged_Attack.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Ranged/Shield_Boss_Ranged_Attack.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Run.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Run/Shield_Boss_Walking_Melee1.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Run/Shield_Boss_Walking_Melee1.png.meta
Labels: Art

#227 Fix #225 Import Drill Boss Sprites
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Death.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Death/Drill_Boss_Death.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Death/Drill_Boss_Death.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Idle.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Idle/Drill_Boss_Idle1.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Idle/Drill_Boss_Idle1.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Melee.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Melee/Drill_Boss_Melee.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Melee/Drill_Boss_Melee.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Range.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Range/Drill_Boss_Ranged.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Range/Drill_Boss_Ranged.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Run.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Run/Drill_Boss_Walking.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Run/Drill_Boss_Walking.png.meta
Labels: Art

#238 Fix #174 Create skeleton death sond
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Skeleton/Audio/FMODSkeleton.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Skeleton/Skeleton Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#242 Fix #241 Create health powerup sound
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/PowerUps/BasePowerUp.cs
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#243 Fix #233 Setup Shield Boss Idle Animation
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/ShieldBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/ShieldBoss.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/IdleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/IdleAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/ShieldBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/ShieldBoss.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Idle/Shield_Boss_Idle_w_spike.png.meta
Labels: Art

#244 Fix #234 Setup Shield Boss Melee Attack Animation
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/ShieldBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/MeleeAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/MeleeAttackAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/ShieldBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Run/Shield_Boss_Walking_Melee1.png.meta
Labels: Art

#245 Fix #235 Setup Shield Boss Ranged Attack Animation
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/RangedAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/RangedAttackAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/ShieldBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Ranged/Shield_Boss_Ranged_Attack.png.meta
Labels: Art

#247 Fix #246 Fix Shield Boss Animations Pivot
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/ShieldBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/MeleeAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/RangedAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Idle/Shield_Boss_Idle_w_spike.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Ranged/Shield_Boss_Ranged_Attack.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Run/Shield_Boss_Walking_Melee1.png.meta
Labels: Art

#248 Fix #236 Setup Shield Boss Death Animation
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/DeathAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/ShieldBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Death/Shield_Boss_Death.png.meta
Labels: Art

#249 Fix #237 Setup Shield Boss Projectile Animation
  Brackeys Game Jam 2020.1/Assets/Prefabs/ShieldBossProjectile.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/ShieldBossProjectile.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/RangedAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/ShieldBossProjectileAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/ShieldBossProjectileAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/Shield_Boss_Projectile_0.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/Shield_Boss_Projectile_0.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Projectile/Shield_Boss_Projectile.png.meta
Labels: Art

#250 Fix #228 Setup Drill Boss Idle Animation
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/DrillBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/DrillBoss.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/DrillBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/DrillBoss.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/IdleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/IdleAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Idle/Drill_Boss_Idle1.png.meta
Labels: Art

#251 FIx #229 Setup Drill Boss Run Animation
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/DrillBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/RunAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/RunAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Run/Drill_Boss_Walking.png.meta
Labels: Art

#252 FIx #230 Setup Drill Boss Melee Attack Animation
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/DrillBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/MeleeAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/MeleeAttackAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Melee/Drill_Boss_Melee.png.meta
Labels: Art

#255 Fix #231 Setup Drill Boss Ranged Attack Animation
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/DrillBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/RangedAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/RangedAttackAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Range/Drill_Boss_Ranged.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Ranged.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Ranged/Drill_Boss_Ranged.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Ranged/Drill_Boss_Ranged.png.meta
Labels: Art

#256 Fix #232 Setup Drill Boss Death Animation
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/DeathAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Animations/DrillBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Death/Drill_Boss_Death.png.meta
Labels: Art

#258 Fix #257 Fix Eye Boss Death Animation
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Eye Boss/EyeBossEnemy.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/DeathAnimation.anim
Labels: Art, Programming

#260 Fix #259 Add Method DestroyEnemy In Enemy Base Script
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/EnemyBase.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Eye Boss/EyeBossEnemy.cs
Labels: Programming

#262 Fix #261 Fix EyeBoss Death Loop When Damaging Again
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Eye Boss/EyeBossEnemy.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/DeathAnimation.anim
Labels: Programming

#265 Fix #263 Switch Between Portals
  Brackeys Game Jam 2020.1/Assets/Prefabs/Player.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/ChangeColor.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/SpriteScript/WeaponHandler.cs
Labels: Art, Programming

#267 Fix #266 Import Last Boss Sprites
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Death.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Death/Final_Boss_Death.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Death/Final_Boss_Death.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Idle.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Idle/Final_Boss_Idle.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Idle/Final_Boss_Idle.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Melee.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Melee/Final_Boss_Melee1.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Melee/Final_Boss_Melee1.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Ranged.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Ranged/Final_Boss_Ranged.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Ranged/Final_Boss_Ranged.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Run.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Run/Final_Boss_Walking.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Run/Final_Boss_Walking.png.meta
Labels: Art

#273 Fix #268 Final Boss Idle Animation Setup
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/FinalBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/FinalBoss.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/FinalBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/FinalBoss.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/IdleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/IdleAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Idle/Final_Boss_Idle.png.meta
Labels: Art

#274 Fix #269 Final Boss Run Animation Setup
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/FinalBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/RunAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/RunAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Run/Final_Boss_Walking.png.meta
Labels: Art

#276 Fix #270 Final Boss Melee Attack Animation Setup
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/FinalBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/MeleeAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/MeleeAttackAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Melee/Final_Boss_Melee1.png.meta
Labels: Art

#277 Fix #271 Final Boss Ranged Attack Animation Setup
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/FinalBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/RangedAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/RangedAttackAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Ranged/Final_Boss_Ranged.png.meta
Labels: Art

#278 FIx #272 Final Boss Death Animation Setup
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/DeathAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/FinalBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Death/Final_Boss_Death.png.meta
Labels: Art

#281 Fix #275 Create eye boss sounds
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Eye Boss/Audio.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Eye Boss/Audio/FMODEyeBoss.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Eye Boss/Audio/FMODEyeBoss.cs.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/MeleeAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/RangedAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/EyeBoss/Animations/RunAnimation.anim
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#282 Fix #279 Import Rock Projectiles Sprites
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Rocks.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Rocks/Drill_Boss_Rock_1-1.png.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Rocks/Drill_Boss_Rock_1-1.png.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Rocks/Drill_Boss_Rock_2-2.png.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Rocks/Drill_Boss_Rock_2-2.png.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Rocks/Drill_Boss_Rock_3-3.png.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Rocks/Drill_Boss_Rock_3-3.png.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Rocks/Drill_Boss_Rock_4-4.png.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/DrillBoss/Rocks/Drill_Boss_Rock_4-4.png.png.meta
Labels: Art

#283 Fix #280 Import Portal Sprites
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Blue.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Blue/Portal.png
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Blue/Portal.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Green.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Green/Portal2.png
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Green/Portal2.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Red.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Red/Portal3.png
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Red/Portal3.png.meta
Labels: Art

#285 Fix #284 Portal Sprites Idle Animation Setup
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/JumpPortalPowerUp.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/JumpPortalPowerUp.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/ShieldPortalPowerUp.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/ShieldPortalPowerUp.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/SpeedPortalPowerUp.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/SpeedPortalPowerUp.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Blue/Animations.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Blue/Animations/IdleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Blue/Animations/IdleAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Blue/Animations/JumpPortalPowerUp.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Blue/Animations/JumpPortalPowerUp.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Blue/Portal.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Green/Animations.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Green/Animations/IdleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Green/Animations/IdleAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Green/Animations/SpeedPortalPowerUp.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Green/Animations/SpeedPortalPowerUp.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Green/Portal2.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Red/Animations.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Red/Animations/IdleAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Red/Animations/IdleAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Red/Animations/ShieldPortalPowerUp.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Red/Animations/ShieldPortalPowerUp.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Red/Portal3.png.meta
Labels: Art

#289 Fix #288 Create DIfferent Cooldowns For The Portals PowerUps
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
Labels: Programming

#291 Fix #290 Check If It's Grounded Before Jump Into Portal
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
Labels: Programming

#294 Fix #292 Fill PowerUp Bar Overtime To Show Player When PowerUp Is Ready
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/HUDScripts/JumpBar.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/HUDScripts/JumpBar.cs.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/HUDScripts/ShieldBar.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/HUDScripts/ShieldBar.cs.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/HUDScripts/speedBar.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/HUDScripts/speedBar.cs.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
Labels: Art, Programming

#296 Fix #295 Create portal switch sound
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#304 Fix #137 Create Shield Portal Control
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/HUDScripts/PowerUpBar.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerManager.cs
Labels: Programming

#306 Fix #305 Touch Enemy Damage
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/EnemyBase.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerManager.cs
Labels: Programming

#309 Fix #307 Allow Player To Activate Power Only After Touch The Portal S…
  Brackeys Game Jam 2020.1/Assets/Prefabs/HUDCanvas.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Player.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/JumpPortalPowerUp.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/ShieldPortalPowerUp.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/SpeedPortalPowerUp.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/HUDScripts/PowerUpBar.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerManager.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/PowerUps/EnablePowerUp.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/PowerUps/EnablePowerUp.cs.meta
Labels: Programming

#312 Fix #311 Make Cooldown Bar Appears after Get PowerUp
  Brackeys Game Jam 2020.1/Assets/Prefabs/HUDCanvas.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/JumpPortalPowerUp.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/ShieldPortalPowerUp.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/SpeedPortalPowerUp.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/PowerUps/EnablePowerUp.cs
Labels: Programming

#314 Fix #313 Create shield boss sounds
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Shield Boss.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Shield Boss/Audio.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Shield Boss/Audio/FMODShieldBoss.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Shield Boss/Audio/FMODShieldBoss.cs.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/DeathAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/MeleeAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/ShieldBoss/Animations/RangedAttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#315 Fix #310 Create Gate Mechanic
  Brackeys Game Jam 2020.1/Assets/Prefabs/Gate.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Gate.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Prefabs/GateCloseInstantly.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/GateCloseInstantly.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Gate.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Gate/ActiveInvisibleWall.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Gate/ActiveInvisibleWall.cs.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Gate/CloseGateInstant.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Gate/CloseGateInstant.cs.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Gate/CloseGateOverTIme.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Gate/CloseGateOverTIme.cs.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Gate/ResetGate.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Gate/ResetGate.cs.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Gate.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Gate/Animations.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Gate/Animations/DoorClosing.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Gate/Animations/DoorClosing.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Gate/Animations/Door_Closing_0.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Gate/Animations/Door_Closing_0.controller.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Gate/Animations/GateClosingAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Gate/Animations/GateClosingAnimation.anim.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/Gate/Door_Closing.png
  Brackeys Game Jam 2020.1/Assets/Sprite/Gate/Door_Closing.png.meta
  Brackeys Game Jam 2020.1/Assets/Sprite/PortalPowerUps/Blue/Animations/JumpPortalPowerUp.controller
Labels: Programming

#318 Fix #317 Fix Shield Boss Touch Damage
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerManager.cs
Labels: Programming

#319 Fix #308 Setup Death when Player Life Hits 0 Or Lesser
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerController.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerManager.cs
Labels: Programming

#321 Fix #320 Change Order In Layer Of Map, Player And Enemies
  Brackeys Game Jam 2020.1/Assets/Prefabs/Bullet.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy Projectiles/BoneProjectile.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy Projectiles/EyeBossProjectile.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy Projectiles/ShieldBossProjectile.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy Projectiles/StoneProjectile.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/BlobEnemy.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/DrillBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/EyeBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/FinalBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/ShieldBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/Skeleton.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/SkeletonEnemy.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Gate.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/GateCloseInstantly.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Map.meta
  Brackeys Game Jam 2020.1/Assets/Prefabs/Map/MainLevelGrid.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Map/MainLevelGrid.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Prefabs/Player.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Portal.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/HealthPowerUP.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/JumpPortalPowerUp.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/ShieldPortalPowerUp.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/PowerUps/SpeedPortalPowerUp.prefab
Labels: Art, Programming

#323 Fix #322 Clear Map
  Brackeys Game Jam 2020.1/Assets/Prefabs/Map/MainLevelGrid.prefab
Labels: Art

#332 Fix level
  Brackeys Game Jam 2020.1/Assets/FinalBossEnemy.cs
  Brackeys Game Jam 2020.1/Assets/GameManager.cs
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/BlobEnemy.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/DrillBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/EyeBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/FinalBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/ShieldBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/SkeletonEnemy.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/FinalBoss.controller
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/FlickAnimation.anim
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/FinalBoss/Animations/FlickAnimation.anim.meta
  Brackeys Game Jam 2020.1/ProjectSettings/TagManager.asset
Labels: Programming

#336 Fix #335 Put Gates Before Bosses
  Brackeys Game Jam 2020.1/Assets/Prefabs/GateCloseInstantly.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Player.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/Levels.unity
Labels: Art, Programming

#341 Fix #340 Create UI sounds and hook up volume control
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Music.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/UI.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/UI.bank.meta
  Brackeys Game Jam 2020.1/Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Brackeys Game Jam 2020.1/Assets/Scenes/MainMenu.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Close.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/MainMenu/SwitchScenes.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Volume/VolumeControllerScript.cs
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Music.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/UI.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/UI.bank.meta
Labels: Audio

#342 Fix #70 Create take damage sound
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerManager.cs
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#343 Fix #337 Put Enemies In The Map
  Brackeys Game Jam 2020.1/Assets/Scenes/Levels.unity
Labels: Art, Programming

#345 Fix #171 Create blob melee sound
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/FX.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.bank
  Brackeys Game Jam 2020.1/Assets/Audio/Desktop/Master.strings.bank
  Brackeys Game Jam 2020.1/Assets/Scenes/SkyHopper's Scene.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Blob/Audio/FMODBlob.cs
  Brackeys Game Jam 2020.1/Assets/Sprite/Enemies/Blob/Blob Animations/AttackAnimation.anim
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/FX.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.bank
  Brackeys Game Jam 2020.1/Assets/StreamingAssets/Master.strings.bank
Labels: Audio

#347 Fix #344
  Brackeys Game Jam 2020.1/Assets/DrillBossEnemy.cs
  Brackeys Game Jam 2020.1/Assets/Prefabs/CM vcam1.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/ClosedGate.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/ClosedGate.prefab.meta
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/EyeBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Map/MainLevelGrid.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/Levels.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/EnemyBase.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Eye Boss/EyeBossEnemy.cs
  Brackeys Game Jam 2020.1/Assets/ShieldBossEnemy.cs
Labels: Programming

#331 Fix #330
  Brackeys Game Jam 2020.1/Assets/Prefabs/Spawner.meta
  Brackeys Game Jam 2020.1/Assets/Prefabs/Spawner/Spawners.prefab
  Brackeys Game Jam 2020.1/Assets/Prefabs/Spawner/Spawners.prefab.meta
Labels: Programming

#350 Fix #348 Disable Enemy Collisions Right After They Die
  Brackeys Game Jam 2020.1/Assets/Prefabs/Map/MainLevelGrid.prefab
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/EnemyBase.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Enemy/Skeleton/SkeletonEnemy.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Player/PlayerManager.cs
Labels: Programming

#357 Fix #352 Use Signs As Tutorial/Tips
  Brackeys Game Jam 2020.1/Assets/Prefabs/Map/Decoration/ReadSign.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/Levels.unity
  Brackeys Game Jam 2020.1/Assets/Scripts/Sign.meta
  Brackeys Game Jam 2020.1/Assets/Scripts/Sign/ReadSign.cs
  Brackeys Game Jam 2020.1/Assets/Scripts/Sign/ReadSign.cs.meta
Labels: Programming

#363 Fix #362 Put Sign Tips For The Player
  Brackeys Game Jam 2020.1/Assets/Scenes/Levels.unity
Labels: Art

#365 Fix #364 decorate level
  Brackeys Game Jam 2020.1/Assets/Prefabs/Map/MainLevelGrid.prefab
Labels: Art

#375 Fix #372 Drill Boss Rock Projectiles Spawning In Ground
  Brackeys Game Jam 2020.1/Assets/DrillBossEnemy.cs
  Brackeys Game Jam 2020.1/Assets/Prefabs/Enemy/DrillBoss.prefab
  Brackeys Game Jam 2020.1/Assets/Scenes/Levels.unity
Labels: Programming, bug
